name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make Run -C 3_Implementation
   
