name: Valgrind

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: sudo apt-get install valgrind
    - name: make
      run: make Run -C 3_Implementation/calculator.c
    - name: Dynamic Analysis
      run: valgrind ./calculator.exe
